const initialState = {
	labels: [],
	files: [],
	snippet: '',
	label: '',
	languages: {
		coffee: 'coffeescript',
		h: 'objective-c',
		bat: 'bat',
		clj: 'clojure',
		cpp: 'cpp',
		cs: 'csharp',
		csp: 'csp',
		dockerfile: 'dockerfile',
		fs: 'fsharp',
		go: 'go',
		graphql: 'graphql',
		handlebars: 'handlebars',
		html: 'html',
		java: 'java',
		js: 'javascript',
		jsx: 'javascript',
		json: 'json',
		lua: 'lua',
		md: 'markdown',
		php: 'php',
		ps1: 'powershell',
		pug: 'pug',
		py: 'python',
		r: 'r',
		rb: 'ruby',
		rs: 'rust',
		swift: 'swift',
		ts: 'typescript',
		xml: 'xml',
		yaml: 'yaml',
		css: 'css',
		less: 'less',
		scss: 'scss',
		txt: 'text'
	}
}

export default initialState
